// Copyright 2021-2023, University of Colorado Boulder

/**
 * Auto-generated from modulify, DO NOT manually modify.
 */
/* eslint-disable */
import getStringModule from '../../chipper/js/getStringModule.js';
import type LocalizedStringProperty from '../../chipper/js/LocalizedStringProperty.js';
import buildANucleus from './buildANucleus.js';

type StringsType = {
  'build-a-nucleus': {
    'title': string;
    'titleStringProperty': LocalizedStringProperty;
  };
  'decay': string;
  'decayStringProperty': LocalizedStringProperty;
  'protonsColon': string;
  'protonsColonStringProperty': LocalizedStringProperty;
  'neutronsColon': string;
  'neutronsColonStringProperty': LocalizedStringProperty;
  'seconds': string;
  'secondsStringProperty': LocalizedStringProperty;
  'halfLifeColon': string;
  'halfLifeColonStringProperty': LocalizedStringProperty;
  'unknown': string;
  'unknownStringProperty': LocalizedStringProperty;
  's': string;
  'sStringProperty': LocalizedStringProperty;
  'lessStable': string;
  'lessStableStringProperty': LocalizedStringProperty;
  'moreStable': string;
  'moreStableStringProperty': LocalizedStringProperty;
  'halfLifeTimescale': string;
  'halfLifeTimescaleStringProperty': LocalizedStringProperty;
  'timeForLightToCrossANucleus': string;
  'timeForLightToCrossANucleusStringProperty': LocalizedStringProperty;
  'timeForLightToCrossAnAtom': string;
  'timeForLightToCrossAnAtomStringProperty': LocalizedStringProperty;
  'timeForLightToCrossOneThousandAtoms': string;
  'timeForLightToCrossOneThousandAtomsStringProperty': LocalizedStringProperty;
  'timeForSoundToTravelOneMillimeter': string;
  'timeForSoundToTravelOneMillimeterStringProperty': LocalizedStringProperty;
  'aBlinkOfAnEye': string;
  'aBlinkOfAnEyeStringProperty': LocalizedStringProperty;
  'oneMinute': string;
  'oneMinuteStringProperty': LocalizedStringProperty;
  'oneYear': string;
  'oneYearStringProperty': LocalizedStringProperty;
  'averageHumanLifespan': string;
  'averageHumanLifespanStringProperty': LocalizedStringProperty;
  'ageOfTheUniverse': string;
  'ageOfTheUniverseStringProperty': LocalizedStringProperty;
  'lifetimeOfLongestLivedStars': string;
  'lifetimeOfLongestLivedStarsStringProperty': LocalizedStringProperty;
  'A': string;
  'AStringProperty': LocalizedStringProperty;
  'B': string;
  'BStringProperty': LocalizedStringProperty;
  'C': string;
  'CStringProperty': LocalizedStringProperty;
  'D': string;
  'DStringProperty': LocalizedStringProperty;
  'E': string;
  'EStringProperty': LocalizedStringProperty;
  'F': string;
  'FStringProperty': LocalizedStringProperty;
  'G': string;
  'GStringProperty': LocalizedStringProperty;
  'H': string;
  'HStringProperty': LocalizedStringProperty;
  'I': string;
  'IStringProperty': LocalizedStringProperty;
  'J': string;
  'JStringProperty': LocalizedStringProperty;
  'availableDecays': string;
  'availableDecaysStringProperty': LocalizedStringProperty;
  'proton': string;
  'protonStringProperty': LocalizedStringProperty;
  'neutronUppercase': string;
  'neutronUppercaseStringProperty': LocalizedStringProperty;
  'neutronLowercase': string;
  'neutronLowercaseStringProperty': LocalizedStringProperty;
  'electron': string;
  'electronStringProperty': LocalizedStringProperty;
  'positron': string;
  'positronStringProperty': LocalizedStringProperty;
  'alphaDecay': string;
  'alphaDecayStringProperty': LocalizedStringProperty;
  'betaMinusDecay': string;
  'betaMinusDecayStringProperty': LocalizedStringProperty;
  'betaPlusDecay': string;
  'betaPlusDecayStringProperty': LocalizedStringProperty;
  'protonEmission': string;
  'protonEmissionStringProperty': LocalizedStringProperty;
  'neutronEmission': string;
  'neutronEmissionStringProperty': LocalizedStringProperty;
  'symbol': string;
  'symbolStringProperty': LocalizedStringProperty;
  'stable': string;
  'stableStringProperty': LocalizedStringProperty;
  'unstable': string;
  'unstableStringProperty': LocalizedStringProperty;
  'doesNotForm': string;
  'doesNotFormStringProperty': LocalizedStringProperty;
  'protons': string;
  'protonsStringProperty': LocalizedStringProperty;
  'neutronsUppercase': string;
  'neutronsUppercaseStringProperty': LocalizedStringProperty;
  'neutronsLowercase': string;
  'neutronsLowercaseStringProperty': LocalizedStringProperty;
  'electronCloud': string;
  'electronCloudStringProperty': LocalizedStringProperty;
  'clusterOfNeutronsPattern': string;
  'clusterOfNeutronsPatternStringProperty': LocalizedStringProperty;
  'availableDecaysInfoPanelText': string;
  'availableDecaysInfoPanelTextStringProperty': LocalizedStringProperty;
  'chartIntro': string;
  'chartIntroStringProperty': LocalizedStringProperty;
  'energy': string;
  'energyStringProperty': LocalizedStringProperty;
  'nuclearShellModel': string;
  'nuclearShellModelStringProperty': LocalizedStringProperty;
  'partialNuclideChart': string;
  'partialNuclideChartStringProperty': LocalizedStringProperty;
  'axis': {
    'protonNumber': string;
    'protonNumberStringProperty': LocalizedStringProperty;
    'neutronNumber': string;
    'neutronNumberStringProperty': LocalizedStringProperty;
  };
  'mostLikelyDecayPattern': string;
  'mostLikelyDecayPatternStringProperty': LocalizedStringProperty;
};

const BuildANucleusStrings = getStringModule( 'BUILD_A_NUCLEUS' ) as StringsType;

buildANucleus.register( 'BuildANucleusStrings', BuildANucleusStrings );

export default BuildANucleusStrings;
